### PR TITLE
Add Access Logging

### PR DESCRIPTION
**Pull request by dansackett**
This Pull Request satisfies #45.

I have tested this with both the default config file and a flag and it seems to work so I'm pushing for critique and hopeful approval into the project.

Access logs can be specified by adding the `accessLog` line to the `conduit.conf` file or by using the `-log` flag with a file path. If the file doesn't exist, the application will attempt to create it. A fatal error will occur if the log is not writable. This brings up my first question: should we fail on log error or should the application continue and simply not log information? Perhaps by default it can log to stdout but I haven't decided where I stand yet.

**To Test**
- Run the vagrant box as usual (rebuilding the code to receive these changes)
- Change directories to `/vagrant/bin` and run `./eps-conduit` without any flags
- If it fails due to permissions, you can use `sudo` to create the file in `/var/log/`
- Run `tail -f /var/log/eps-conduit.log` in another terminal session
- Navigate your browser to `127.0.0.1:8000` and see that the log populates
- Stop the conduit and run it again this time with a flag `./eps-conduit -log/tmp/test.log` and tail this file and see that it writes there

**Format**

The format chosen is similar to Amazon ELB logs where each line will look like:

```
timestamp load_balancer_id load_balancer_ip:port client_ip:port request_latency request_bytes response_bytes protocol status_code "request_string" "user_agent"
```

An example is:

```
2016-02-08T03:50:21Z 1 127.0.0.1:8002 10.0.2.2:50348 1.262676ms 0 62 HTTP/1.1 200 "GET 127.0.0.1:8000/ HTTP/1.1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
```

Let me know if we should make some changes or if this is an acceptable logging mechanism!

### CODE REVIEW

**Comment by scottcrespo** [comment]
@dansackett 

Thanks for submitting! Glad to see some movement here. I'm in the process of testing.

**Comment by scottcrespo** [comment]
@dansackett 

Didn't work for me. Have any insight as to why?

### Ran eps-conduit as sudo

`vagrant@vagrant-ubuntu-trusty-64:/vagrant/bin$ sudo ./eps-conduit`

`2016/02/21 15:47:17 using 127.0.0.1:8001 as a backend`

`2016/02/21 15:47:17 using 127.0.0.1:8002 as a backend`

`2016/02/21 15:47:17 listening on port 8000`

### Requested localhost:8000

`$ curl localhost:8000`

`Hello world, I'm answering your request from backend port 8002`

`$ curl localhost:8000`

`Hello world, I'm answering your request from backend port 8001`

### Attempted to tail the log file, received "No such file or directory"

`vagrant@vagrant-ubuntu-trusty-64:~$ tail -f /var/log/eps-conduit.log`
`tail: cannot open ‘/var/log/eps-conduit.log’ for reading: No such file or directory`

### Confirmed log file does not exist

`vagrant@vagrant-ubuntu-trusty-64:~$ ls /var/log`
`alternatives.log  btmp                   dist-upgrade  fsck       puppet       unattended-upgrades`
`apt               chef                   dmesg         kern.log   supervisord  upstart`
`auth.log          cloud-init.log         dmesg.0       landscape  syslog       wtmp`
`boot.log          cloud-init-output.log  dpkg.log      lastlog    udev`

**Comment by scottcrespo** [comment]
@dansackett 

### Success

Looks like I was running the wrong `eps-conduit` executable. when I specified the full path (`/vagrant/bin/eps-conduit`) or specified the current directory's executable (`./eps-conduit`) everything worked as expected.

**Comment by scottcrespo** [comment]
@dansackett 

The implementation is really good. I have one question/recommendation:

Would it make sense to move `log.go` into a "middleware" package [directory]?

I think this could help keep the main project directory cleaner. And, I could foresee us adding additional middleware in the future. Thus, having a dedicated middleware package today sets us up to handle greater scale and complexity in the future.

Your thoughts?

**Comment by dansackett** [comment]
Hey @scottcrespo thanks for testing this!

I agree, I like the idea of middleware being a subdirectory within the conduit structure so we can easily add new pieces as ideas come together. What I propose we do is make a new pull request for this (after this has been accepted and pulled in) because after thinking about things, I think I want to steal an idea from [Redux](https://github.com/reactjs/redux) where we create a utility function called `ApplyMiddleware()` that can wrap the request handler.

I can flesh this out in a more concise plan in a new issue but what I'm thinking is perhaps we do something like:

```
type Middleware interface {
    Handle(http.HandlerFunc) http.HandlerFunc
}

type LoggingMW struct{}
var LoggingMiddleware LoggingMiddleware

func (m LoggingMiddleware) Handle(fn http.HandlerFunc) http.HandlerFunc {
...
}

func ApplyMiddleware(mw []Middleware, fn http.HandlerFunc) http.HandlerFunc {
    for _, m := range mw {
        fn = mw.Handle(fn)
    }
    return fn
}
```

With this, then we can just do this in the `main.go` file:

```
middlewares := []Middleware{
    LoggingMiddleware,
    SomeOtherMiddleware,
}

http.HandleFunc("/", ApplyMiddleware(middlewares, config.handle))
```

I don't know if that code will actually compile or do what I'm expecting but it's a general implementation idea for keeping our codebase clean and giving middleware a common interface to conform to. What do you think?

As for this PR, what are your thoughts about this crashing if a log file cannot be logged to? I don't know if it should be addressed so uses can choose not to log or if logging is enforced (this enforces it).

**Comment by scottcrespo** [comment]
@dansackett 

Cool. Then lets accept this PR and subsequently refactor into a middleware package.

Actually, they way you're proposing to chain the middleware can been done pretty well with a tool called [Alice](https://github.com/justinas/alice). I definitely recommend this library. I've used it myself with good results. 

Yes, this PR does introduce the requirement to run as sudo when using the default log path. However, most tools do the same. So I think if we just have a blurb in the README about it, we're good.

**Pull request merged**
